language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

addons:
  apt:
    update: true
    sources:
    - sourceline: "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8"
      key_url: "https://bazel.build/bazel-release.pub.gpg"
    packages:
      - bazel

install:
  - pip install --upgrade pip
  - pip install --upgrade tf-nightly tensorflow-probability==0.8.0 numpy attrs scipy

script:
  - bazel test tf_quant_finance/... --test_summary=detailed --test_output=errors


